image: golang:1.16

stages:
- format
- test
- unit

include:
- template: Security/SAST.gitlab-ci.yml
- template: Security/Dependency-Scanning.gitlab-ci.yml

vet:
    stage: format
    script:
    - go vet ./...

golint:
  stage: format
  script:
    - go install golang.org/x/lint/golint@latest
    - golint -set_exit_status ./...

staticcheck:
  stage: test
  script:
    - go install honnef.co/go/tools/cmd/staticcheck@v0.3.0
    - staticcheck ./...

unit-test:
    stage: unit
    script:
      - make test-unit

coverage:
    stage: unit
    script:
      - make test-coverage
