version: "3.7"

services:
  pubsub-emulator:
    image: gcr.io/google.com/cloudsdktool/cloud-sdk:latest
    ports:
      - "8085:8085"
    command: ["gcloud", "beta", "emulators", "pubsub", "start", "--project", "serverless-mapreduce", "--host-port", "0.0.0.0:8085"]