version: "3.7"

services:
  shuffler-cloud-run:
    build:
      context: .
      dockerfile: controller/Dockerfile
  pubsub-emulator:
    image: gcr.io/google.com/cloudsdktool/cloud-sdk:latest
    ports:
      - "8085:8085"
    command: ["gcloud", "beta", "emulators", "pubsub", "start", "--project", "serverless-mapreduce", "--host-port", "0.0.0.0:8085"]
  storage-emulator:
    image: oittaa/gcp-storage-emulator
    environment:
      - PORT=9023
    expose:
      - "9023"
    volumes:
      - ${PWD}/cloudstorage:/storage