swagger: "2.0"
info:
  title: Serverless MapReduce API
  description: API to start running mapreduce on input bucket and store anagrams in output bucket
  version: 1.0.0
paths:
  /startMapreduce:
    post:
      summary: Start mapreduce
      description: Starts mapreduce on input bucket and stores anagrams in output bucket
      operationId: startMapreduce
      x-google-backend:
        address: https://europe-west2-serverless-mapreduce.cloudfunctions.net/start-mapreduce
      parameters:
        - name: inputBucket
          in: query
          description: Input bucket
          required: true
          type: string
      responses:
        '200':
          description: OK
          schema:
              $ref: '#/definitions/StartMapreduce200Response'
        '400':
          description: Bad Request
          schema:
            $ref: '#/definitions/StartMapreduce400Response'
        '500':
          description: Internal Server Error
          schema:
            $ref: '#/definitions/StartMapreduce500Response'

definitions:
  StartMapreduce200Response:
    type: object
    properties:
      message:
        type: string
        description: 200 response message
  StartMapreduce400Response:
      type: object
      properties:
          message:
            type: string
            description: 400 response message
  StartMapreduce500Response:
    type: object
    properties:
        message:
          type: string
          description: 500 response message
